name: MoltenVK
on:
    push:
        branches-ignore:
            - "ci/**"
            - "develop/**"
            - "main"
        paths:
            - build/submodules/MoltenVK
            - build/nuke/Native/Core.cs
            - build/nuke/Native/MoltenVK.cs
            - .github/workflows/moltenvk.yml
jobs:
    Build:
        if: github.repository == 'dotnet/Silk.NET'
        strategy:
            fail-fast: false
            matrix:
                env:
                    - os: macos-13-xlarge
                      name: Darwin
                      nuke_invoke: ./build.sh
                      extras: ""
        name: ${{ matrix.env.name }} Build
        runs-on: ${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

            - name: Checkout submodules, configure git
              run: |
                  git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive build/submodules/MoltenVK
                  git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
                  git config --local user.name "The Silk.NET Automaton"

            - name: Extra prerequisites
              run: |
                  echo running extras
                  ${{ matrix.env.extras }}

            # Install python
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            # Install CMake and Ninja
            - uses: lukka/get-cmake@latest

            - name: Build MoltenVK
              run: ${{ matrix.env.nuke_invoke }} MoltenVK
              env:
                  PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
