name: Vkd3d
on:
  push:
    branches-ignore:
      - "ci/**"
      - "develop/**"
      - "main"
    paths:
      - build/submodules/vkd3d
      - build/submodules/SPIRV-Tools
      - build/submodules/Vulkan-Headers
      - "build/cmake/*"
      - build/nuke/Native/Core.cs
      - build/nuke/Native/Vkd3d.cs
      - .github/workflows/vkd3d.yml
      - src/Microsoft/Vkd3dCompiler/*
jobs:
  Build:
    if: github.repository == 'dotnet/Silk.NET'
    strategy:
      fail-fast: false
      matrix:
        env:
          - os: ubuntu-22.04
            name: Linux
            nuke_invoke: ./build.sh
            extras: |
              # We need to adjust APT sources for multiarch. Use the ones corresponding to
              # Ubuntu 22.04 with appropriate `arch` values. ports.ubuntu.com is required
              # for armhf and arm64.
              sudo tee /etc/apt/sources.list << EOF
              deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main universe
              deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-backports main universe
              deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-security main universe
              deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main universe
              deb [arch=arm64,armhf] http://ports.ubuntu.com jammy main universe
              deb [arch=arm64,armhf] http://ports.ubuntu.com jammy-backports main universe
              deb [arch=arm64,armhf] http://ports.ubuntu.com jammy-security main universe
              deb [arch=arm64,armhf] http://ports.ubuntu.com jammy-updates main universe
              deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy main universe
              deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy-backports main universe
              deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy-security main universe
              deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy-updates main universe
              EOF
              sudo dpkg --add-architecture arm64
              sudo dpkg --add-architecture armhf
              sudo apt update
              sudo apt install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
              sudo apt install -y g++-aarch64-linux-gnu g++-arm-linux-gnueabihf
              sudo apt install -y mingw-w64-tools
    name: ${{ matrix.env.name }} Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
      - name: Checkout submodules, configure git
        run: |
          git submodule update --init --recursive --depth 0 build/submodules/vkd3d
          git submodule update --init --recursive --depth 0 build/submodules/SPIRV-Tools
          git submodule update --init --recursive --depth 0 build/submodules/Vulkan-Headers
          git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
          git config --local user.name "The Silk.NET Automaton"
      - name: Extra prerequisites
        run: |
          echo running extras
          ${{ matrix.env.extras }}
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Setup .NET 6.0 and .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.201
            7.0.*
      - name: Build vkd3d
        run: ${{ matrix.env.nuke_invoke }} Vkd3d
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

